---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-deploy
  labels:
    app:  addressbook
spec:
  replicas: 10 
  selector:
    matchLabels:
      app:  addressbook
  template:
    metadata:
      labels:
         app: addressbook
    spec:
     containers:
     - name: addressbook-pod
       image: rm150623/addressbook:36
       ports:
       - containerPort: 8080
