---
apiVersion: v1
kind: Service
metadata:
 name: addressbook-svc
 labels:
   app: addressbook-svc
spec:
  type: NodePort
  ports:
   - port: 8080
     nodePort: 30005
     protocol: TCP
  selector:
   app: addressbook
